[tool.poetry]
name = "brewval"
version = "0.0.1"
description = "Evaluating prompts on all LLMs"
authors = []
license = "MIT"
readme = "README.md"
repository = "https://github.com/BrewLLM/brewval"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.0.76"
